// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-listings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/catalog.ts
var categories = [
  { name: "Electronics", listings: "24,320" },
  { name: "Vehicles", listings: "18,912" },
  { name: "Real Estate", listings: "9,204" },
  { name: "Jobs", listings: "6,540" },
  { name: "Furniture", listings: "12,830" },
  { name: "Fashion", listings: "31,215" },
  { name: "Home & Garden", listings: "10,120" },
  { name: "Sports", listings: "7,410" },
  { name: "Books", listings: "5,320" },
  { name: "Pets", listings: "2,910" },
  { name: "Services", listings: "8,725" },
  { name: "Other", listings: "3,411" }
];
var listings = [
  { id: "1", title: "Leica M-A Rangefinder Camera", price: "\u20AC2,450", location: "Paris 3e, FR", postedAgo: "2h ago", rating: 4.9, category: "Electronics", featured: false },
  { id: "2", title: "Scandinavian Oak Armchair", price: "\u20AC320", location: "Lyon, FR", postedAgo: "5h ago", rating: 4.8, category: "Furniture", featured: false },
  { id: "3", title: "VanMoof S5 Electric Bike", price: "\u20AC1,890", location: "Bordeaux, FR", postedAgo: "1d ago", rating: 4.7, category: "Sports", featured: false },
  { id: "4", title: 'MacBook Pro 14" M3 \u2014 Mint', price: "\u20AC1,650", location: "Marseille, FR", postedAgo: "3h ago", rating: 5, category: "Electronics", featured: false },
  { id: "5", title: "Omega Seamaster Deville", price: "\u20AC2,100", location: "Nice, FR", postedAgo: "1d ago", rating: 4.9, category: "Fashion", featured: false },
  { id: "6", title: "Sunlit 2BR Apartment \u2014 Downtown", price: "\u20AC1,450/mo", location: "Toulouse, FR", postedAgo: "6h ago", rating: 4.8, category: "Real Estate", featured: false },
  { id: "f1", title: "Loft 90m\xB2 \xB7 Balcony \xB7 Herringbone floors", price: "\u20AC1,450/mo", location: "Toulouse, FR", postedAgo: "Featured", rating: 4.9, category: "Real Estate", featured: true },
  { id: "f2", title: 'MacBook Pro 14" M3 \xB7 AppleCare+', price: "\u20AC1,650", location: "Marseille, FR", postedAgo: "Featured", rating: 5, category: "Electronics", featured: true },
  { id: "f3", title: "VanMoof S5 \xB7 500 km \xB7 Full warranty", price: "\u20AC1,890", location: "Bordeaux, FR", postedAgo: "Featured", rating: 4.8, category: "Sports", featured: true }
];
var designTokens = {
  primary: "#4A235A",
  secondary: "#6C3483",
  accent: "#294541",
  background: "#F8F7F5",
  surface: "#FFFFFF",
  text: "#1F2937",
  border: "#E5E7EB",
  success: "#22C55E",
  typography: "Inter",
  spacing: "8px base scale"
};

// src/lib/mcp/tools/search-listings.ts
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search listings",
  description: "Search the public Venditu marketplace listings by keyword, category, or featured status.",
  inputSchema: {
    query: z.string().optional().describe("Keyword matched against listing title and location."),
    category: z.string().optional().describe("Category name, e.g. Electronics."),
    featured_only: z.boolean().optional().describe("Return only featured listings."),
    limit: z.number().int().optional().describe("Maximum number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category, featured_only, limit }) => {
    const q = query?.trim().toLowerCase();
    const cat = category?.trim().toLowerCase();
    const max = Math.min(Math.max(limit ?? 10, 1), 50);
    const results = listings.filter((l) => featured_only ? l.featured : true).filter((l) => cat ? l.category.toLowerCase() === cat : true).filter(
      (l) => q ? l.title.toLowerCase().includes(q) || l.location.toLowerCase().includes(q) : true
    ).slice(0, max);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.24.2";
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get listing",
  description: "Get the full details of one public Venditu listing by its id.",
  inputSchema: { id: z2.string().describe("Listing id, e.g. '1' or 'f2'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const listing = listings.find((l) => l.id === id);
    if (!listing) throw new ToolError(`No listing found with id "${id}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(listing, null, 2) }],
      structuredContent: { listing }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List the public Venditu marketplace categories and their listing counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
    structuredContent: { categories }
  })
});

// src/lib/mcp/tools/get-design-system.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_design_system_default = defineTool4({
  name: "get_design_system",
  title: "Get design system",
  description: "Return the public Venditu design system tokens (colors, typography, spacing scale).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(designTokens, null, 2) }],
    structuredContent: { tokens: designTokens }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "venditu-design-system",
  title: "Venditu Design System",
  version: "0.1.0",
  instructions: "Public tools for the Venditu marketplace landing page. Use `list_categories` to browse categories, `search_listings` to find listings by keyword/category, `get_listing` for one listing's details, and `get_design_system` for the brand's design tokens.",
  tools: [search_listings_default, get_listing_default, list_categories_default, get_design_system_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
